# Generated by Django 5.2.4 on 2025-07-09 20:07

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Author's full name", max_length=200),
                ),
                (
                    "bio",
                    models.TextField(
                        blank=True, help_text="Brief biography of the author"
                    ),
                ),
                (
                    "website",
                    models.URLField(blank=True, help_text="Author's official website"),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, help_text="Author's birth date", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Author",
                "verbose_name_plural": "Authors",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(help_text="Book title", max_length=300)),
                (
                    "genre",
                    models.CharField(
                        choices=[
                            ("fiction", "Fiction"),
                            ("non-fiction", "Non-Fiction"),
                            ("mystery", "Mystery & Thriller"),
                            ("romance", "Romance"),
                            ("sci-fi", "Science Fiction"),
                            ("fantasy", "Fantasy"),
                            ("biography", "Biography & Memoir"),
                            ("history", "History"),
                            ("self-help", "Self-Help"),
                            ("business", "Business"),
                            ("other", "Other"),
                        ],
                        default="fiction",
                        max_length=20,
                    ),
                ),
                (
                    "isbn",
                    models.CharField(
                        blank=True, help_text="ISBN-13 number", max_length=13
                    ),
                ),
                (
                    "publication_date",
                    models.DateField(
                        blank=True, help_text="Date of publication", null=True
                    ),
                ),
                (
                    "page_count",
                    models.PositiveIntegerField(
                        blank=True, help_text="Number of pages", null=True
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, help_text="Book description/summary"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="book_covers/"),
                ),
                ("slug", models.SlugField(blank=True, max_length=300, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="blog.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "verbose_name_plural": "Books",
                "ordering": ["-publication_date", "title"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(help_text="Review title", max_length=200)),
                ("content", models.TextField(help_text="Review content")),
                (
                    "is_public",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this review is publicly visible",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="blog.book",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
                "ordering": ["-created_at"],
                "unique_together": {("book", "reviewer")},
            },
        ),
    ]
