# Generated by Django 5.2.4 on 2025-07-16 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="author",
            name="profile_image",
            field=models.ImageField(
                blank=True,
                help_text="Author's profile photo",
                null=True,
                upload_to="author_photos/",
            ),
        ),
    ]
