# Generated by Django 4.2.23 on 2025-07-31 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_author_profile_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="BackdropImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Descriptive name for the backdrop", max_length=200
                    ),
                ),
                (
                    "original_image",
                    models.ImageField(
                        help_text="Original high-resolution backdrop image",
                        upload_to="site_images/backdrops/",
                    ),
                ),
                (
                    "processed_image",
                    models.ImageField(
                        blank=True,
                        help_text="Processed version for web use",
                        null=True,
                        upload_to="site_images/backdrops/processed/",
                    ),
                ),
                (
                    "processing_style",
                    models.CharField(
                        choices=[
                            ("original", "Original Color"),
                            ("desaturated", "Low Saturation"),
                            ("sepia", "Sepia Tone"),
                            ("greyscale", "Greyscale"),
                        ],
                        default="desaturated",
                        help_text="How the image should be processed",
                        max_length=20,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this backdrop is available for use",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Backdrop Image",
                "verbose_name_plural": "Backdrop Images",
                "ordering": ["name"],
            },
        ),
    ]
