# Generated by Django 4.2.23 on 2025-08-02 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_backdropimage"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                help_text="Review status",
                max_length=20,
            ),
        ),
    ]
