# Generated by Django 4.2.23 on 2025-08-03 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_review_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="book_images",
            field=models.ImageField(
                blank=True,
                help_text="Images of the open book for the review",
                null=True,
                upload_to="open_book_images/",
            ),
        ),
        migrations.AlterField(
            model_name="backdropimage",
            name="processing_style",
            field=models.CharField(
                choices=[
                    ("original", "Original Color"),
                    ("desaturated", "Low Saturation"),
                    ("sepia", "Sepia Tone"),
                    ("greyscale", "Greyscale"),
                    ("whitened", "Whitened Backdrop"),
                ],
                default="desaturated",
                help_text="How the image should be processed",
                max_length=20,
            ),
        ),
    ]
